### ISSUE TITLE
Annotation viz disappear on track reorder

### ISSUE THREAD

**Issue by scalefreegan** [baliga-lab/GGBWeb#17]
**Before**

![screen shot 2015-02-09 at 11 13 10 am](https://cloud.githubusercontent.com/assets/1069467/6113501/b86b18d6-b04c-11e4-97fd-b8bc051c331a.png)

**After**

![screen shot 2015-02-09 at 11 13 55 am](https://cloud.githubusercontent.com/assets/1069467/6113513/c86d8d2c-b04c-11e4-9647-3fae5f421596.png)

**Comment by scalefreegan** [comment]
Additional note: only happens when more than one window is active

**Comment by dsalvanha** [comment]
fixed. please, pull.
