### ISSUE TITLE
default annotation lane should "snap" to annotation track size

### ISSUE THREAD

**Issue by scalefreegan** [baliga-lab/GGBWeb#18]
_What it does now_

![screen shot 2015-02-09 at 11 17 21 am](https://cloud.githubusercontent.com/assets/1069467/6113579/4259aa12-b04d-11e4-81fa-0a204fc67814.png)

_What is should do_

![screen shot 2015-02-09 at 11 17 58 am](https://cloud.githubusercontent.com/assets/1069467/6113601/68d986a8-b04d-11e4-979a-554e398e4625.png)

**Comment by dsalvanha** [comment]
Once we create GGBWindow, we don't have lane information to figure out what's the width/hight needed - so in first instance, I've set a new lane default height to 80px.
