### ISSUE TITLE
Lane configuration - decision

### ISSUE THREAD

**Issue by dsalvanha** [baliga-lab/GGBWeb#21]
priority: low

Right now whenever the user adds/remove a new track it happens on cascade (on all available GGBwindow).

It would be a really nice feature to have a configuration buttons saying: enable/desable sync between GGBwindows. (I know it is a complicatade rule to implement - that's the reason it is a question-flaged) issue.

The user might want to add/remove a specific lane to only one GGBwindow

**Comment by njiang** [comment]
I've asked Aaron and seems he feels the unsynced case is very rare.  Do we still feel this way?
