### ISSUE TITLE
Line plot inconsistent rendering with microarray data

### ISSUE THREAD

**Issue by scalefreegan** [baliga-lab/GGBWeb#26]
Sometimes line plot fills the entire window, sometimes only a small region. Contrast two images below:

![image](https://cloud.githubusercontent.com/assets/1069467/6254782/f983ccea-b75f-11e4-823e-0390743c8d2b.png)

![image](https://cloud.githubusercontent.com/assets/1069467/6254806/2c146d9a-b760-11e4-8482-3d5b37900ab7.png)

**Comment by dsalvanha** [comment]
Which data r u using ?

from db or flat file ? if flat-file, please attach it here.

**Comment by scalefreegan** [comment]
database. 

sounds like you are aware and on top of this issue

**Comment by dsalvanha** [comment]
Microarray data (expression) and line chart might be inconsistent most (all) of the time, right ?

Microarray data is always segment (probe based) (with start and end)
data example:
locus, start, end, strand, value
chr,1,10,+,-1
chr,100,200,+,-2
chr,500,682,+,0.3

How do we expect a line chart to draw correctly ? In this case, I can fill the "gaps" with 0  or null  (transform data to sampling rate of 1), but the line chart will be really ugly - and not really a line chart. see image attached.

PS. ("minding the gap" is expensive on redrawing - panning/zooming)

![line-chart-filled-with-zeros](https://cloud.githubusercontent.com/assets/3534677/6266793/f92ed2ce-b824-11e4-9845-fef718eb2a5d.png)

@scalefreegan - with the user hat, what would you expect ?

**Comment by scalefreegan** [comment]
Weird. I'm not seeing the update you posted here, Diego. I got the email but your reply is missing...

I see your point and the example you included is quite ugly...

For microarray data I would expect to see line segments across the entire gene body. Are you only representing the value at a gene's start position? I think every position within the gene body should inherit the value - so it is pretty much a line 'segment'. 

Does this make sense?

W/ respect to performance, we need to consider how to represent "lines" at different scales. If it is too expensive to draw a line, we should aggregate individual values together (basically segments again). At some scales maybe the whole viz will have to change...?

**Comment by dsalvanha** [comment]
Option 1: (gap on line chart)

![image](https://cloud.githubusercontent.com/assets/3534677/6271006/0473c354-b845-11e4-9a83-f83d81c67ea6.png)

Option 2: (interpolates to zero on gaps - this might be a problem to rescale data - but I can find a way to do so) (somehow gives us a fake impression of values )

![image](https://cloud.githubusercontent.com/assets/3534677/6271042/4ffc33a6-b845-11e4-8d0f-f43034a70d9e.png)

**Comment by scalefreegan** [comment]
I like option 2 best, as long as it's not too crazy to rescale. this is exactly what i was imagining 

would it be possible to add an (optional) line at 0 for reference? light stroke, dotted/dashed

**Comment by dsalvanha** [comment]
Option 2 it is. solved rescaling issue as well. Tons of refactoring.  
- would it be possible to add an (optional) line at 0 for reference? light stroke, dotted/dashed
  yes, it would. reference line should always be centered ? (0 only if center == 0)
  done.

Please pull.
