### ISSUE TITLE
Previous data not removed on 'Visulalization Type' change

### ISSUE THREAD

**Issue by scalefreegan** [baliga-lab/GGBWeb#27]
Here heatmap, line, and segments are all plotted and never removed when changing 'Viz Type' in settings panel 

![image](https://cloud.githubusercontent.com/assets/1069467/6254839/5fc6c2fa-b760-11e4-8c6d-ef9f079badc9.png)

**Comment by dsalvanha** [comment]
Also fixed the same issue whenever user has more then 1 GGBwindow openned. Should work properly now.
