### ISSUE TITLE
#5 - Checkbox for data itens [to implement]

### ISSUE THREAD

**Issue by dsalvanha** [baliga-lab/GGBWeb#36]
We should have the ability of check multiple icons (or all at once) and load it.

Data item (tracks) --> all selections should be added as a track into a lane. User picks a lane or create a new one and we render all tracks at once.

Checkboxes for selection are hidden by default and there is a new icon close to each data group that activates multiple selections:

![image](https://cloud.githubusercontent.com/assets/3534677/6760309/a1396c4a-cf04-11e4-8d8c-25a7c5c3ea9d.png)

**Comment by njiang** [comment]
Done.
