### ISSUE TITLE
reduce ajaxcalls as much as possible

### ISSUE THREAD

**Issue by dsalvanha** [baliga-lab/GGBWeb#4]
So, each new lane ajax call separetelly. It is not good at all.

We need to find a way (maybe a controller) to ajax call only once and split the data to the right lanes.

AJAX-call reduction design is needed - Let's discuss solutions ?

**Comment by njiang** [comment]
We already implemented the ajax reduction mechanism.  ggbwindow loads data for each window, not each lane.  When user pan/zoom x axis, we make ajax call to fetch all predefined tracks if necessary.  And then we inform all the lanes to redraw.  When user adds a new lane, we use the saved data. No ajax call is made.

**Comment by dsalvanha** [comment]
We should keep this issue open - once we are not yet done with ajaxcalls.

**Comment by dsalvanha** [comment]
we don't care about it anymore. all local.
